<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="swscheme2.xsl" type="text/xsl"?>
<!DOCTYPE doc [
  <!ELEMENT doc (maintitle, section*)>
  <!ELEMENT maintitle (#PCDATA)>
  <!ELEMENT section (title, (p|ul|ulp|section)*)>
  <!ATTLIST section name CDATA #IMPLIED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT ul (li|ul)*>
  <!ELEMENT ulp (li|ul|ulp)*>
  <!ELEMENT li (#PCDATA | code | var | i | b | xref | link)*>
  <!ELEMENT p (#PCDATA | code | var | i | b | xref | link)*>
  <!ELEMENT code (#PCDATA | var)*>
  <!ELEMENT var (#PCDATA)>
  <!ELEMENT xref EMPTY>
  <!ATTLIST xref dest CDATA #IMPLIED>
  <!ELEMENT link (#PCDATA)>
  <!ATTLIST link url CDATA #IMPLIED>
  <!ELEMENT i (#PCDATA)>
  <!ELEMENT b (#PCDATA)>
  <!ENTITY lt "&#38;#60;">
  <!ENTITY gt "&#62;">
  <!ENTITY amp "&#38;#38;">
  <!ENTITY apos "&#39;">
  <!ENTITY quot "&#34;">
  <!ENTITY ndash "&#8211;">
  <!ENTITY mdash "&#8212;">
  <!ENTITY lsquo "&#8216;">
  <!ENTITY rsquo "&#8217;">
  <!ENTITY ldquo "&#8220;">
  <!ENTITY rdquo "&#8221;">
]>
<!-- formatted to 118 chars width -->
<doc>

<maintitle>Sunlit World Scheme</maintitle>

<section name="intro"><title>Introduction</title>

<p>(This document is part of Sunlit World Scheme, Copyright © 2010 by Edward Kiser. Licensed under the terms of the
GNU General Public License, version 2 or later. All other rights reserved.)</p>

<p>Scheme is an elegant programming language that allows you to construct a program out of a collection of simple but
powerful nestable building blocks.</p>

<p>Sunlit World Scheme is my own implementation. It is a work in progress and, at present, only partially conforms to
the Scheme standards.</p>

<p>This instruction manual is written to describe what building blocks are available. It assumes prior knowledge of
programming, and, in cases where it can&rsquo;t be helped, it assumes prior knowledge of Scheme.</p>

<section name="rationale"><title>Why Sunlit World Scheme?</title>

<p>Sunlit World Scheme can do things that no other Scheme can do. It&rsquo;s exactly that simple. This manual
documents the sorts of things that Sunlit World Scheme can do. If you want a Scheme that can do these things, then
Sunlit World Scheme is the Scheme for you.</p>

<p>Sunlit World Scheme is designed to emphasize interactive graphics, sockets, asynchronous message passing, and
low-level bit and byte manipulation. It is also designed to be very easy to extend.</p>

<p>Sunlit World Scheme was started a long time ago, when other Scheme implementations were less mature than they are
today. There are a few things that other Schemes can do that Sunlit World Scheme cannot do. If you need those things,
then you would probably be happier with another Scheme
implementation. (<link url="http://dynamo.iro.umontreal.ca/~gambit/wiki/index.php/Main_Page">Gambit Scheme</link> is
pretty good. If you need another Scheme that is compatible with dot-Net,
consider <link url="http://ironscheme.codeplex.com/">Iron Scheme</link>.)</p>

</section>

<section name="notational"><title>Notational Conventions</title>

<p>This document looks best in Firefox although it seems to be legible in Internet Explorer. (IE7 and IE8 don&rsquo;t
seem to handle the title of the &ldquo;And&rdquo; and &ldquo;Or&rdquo; section quite right, or entities generally in
some cases). IE6 has not been tested.</p>

<p><code>This font</code> is used for code, which must be typed exactly as shown.</p>

<p><var>This font</var> is used for variables, which must be replaced with appropriate values.</p>

<p>If a variable is followed by ellipses, zero or more instances of the variable may occur. In other words, where this
document calls for <code>(<var>blah</var> <var>...</var>)</code>, <code>()</code> is acceptable. If one or more
instances are required, the requirement will be written as <code>(<var>blah</var> <var>blah</var>
<var>...</var>)</code>.</p>

</section>

</section>

<section name="datatypes"><title>Data Types</title>

<p>Scheme is a <i>weakly typed</i> language. A data item knows its own type (which makes Scheme more strongly typed
than Forth or assembly language), but a variable, a parameter, or an argument can be of any type.</p>

<p>Here are the types supported by Sunlit World Scheme.</p>

<section name="boolean"><title>Booleans</title>

<p>The booleans are <code>#t</code> (true) and <code>#f</code> (false).</p>

</section>

<section name="integers"><title>Integers</title>

<p>Sunlit World Scheme supports arbitrary-precision integers.</p>

<p>An integer is written as an optional sign (<code>+</code> or <code>-</code>) followed by a sequence of one or more
decimal digits. Examples include <code>4578926458734658237456</code> and <code>-1</code>. A integer can be written in
hexadecimal as an optional sign followed by <code>#x</code> followed by a sequence of one or more hexadecimal digits,
for example <code>-#x100</code>. The hexadecimal digits <code>A</code> through <code>F</code> are
case-insensitive. Sunlit World Scheme cannot currently read an octal integer, but there are functions to convert
between integers and digit strings in bases 2 through 36.</p>

</section>

<section name="rationals"><title>Rationals</title>

<p>A rational is written with an optional sign, followed by a sequence of one or more decimal digits, followed by a
slash, followed by another sequence of one or more decimal digits. For example, <code>1/2</code> or
<code>-2/3</code>.</p>

<p>Rationals, like integers, are exact and have arbitrary precision.</p>

</section>

<section name="floats"><title>Floating-Point Numbers</title>

<p>Sunlit World Scheme uses IEEE 64-bit floating-point numbers for inexact math.</p>

<p>There are several ways in which a floating-point number may be written. The most common form is like an integer but
with a decimal point somewhere among the digits. The decimal point must come after the optional
sign. <code>-3.5</code>, <code>-35.</code>, and <code>+.35</code> are all floats. It is also possible to create a
floating-point number that has an exponent. In this case, an explicit decimal point is not required. The sign of the
exponent is presumed to be <code>+</code> if not specified. Floating-point numbers with exponents include
<code>1.E+10</code>, <code>1E10</code>, and <code>-2E-3</code>.</p>

<p>See also <xref dest="func_math"/>.</p>

</section>

<section name="vec3d"><title>3-D Geometry</title>

<p>Sunlit World Scheme supports several types for exact 3-D geometry.</p>

<ulp>

<li><b>Vectors.</b> A 3-D vector is written <code>#vec3(<var>x</var> <var>y</var> <var>z</var>)</code>
where <var>x</var>, <var>y</var>, and <var>z</var> are integers or rational numbers. Vectors are used to represent
displacements.</li>

<li><b>Vertices.</b> A 3-D vertex is written <code>#vtx3(<var>x</var> <var>y</var> <var>z</var>)</code>
where <var>x</var>, <var>y</var>, and <var>z</var> are integers or rational numbers. Vertices are used to represent
positions in 3-D space.</li>

<li><b>Lines.</b> A 3-D line object cannot be entered directly, but can be returned as a function result. 3-D lines
are infinite.</li>

<li><b>Planes.</b> A 3-D plane object cannot be entered directly, but can be returned as a function result. 3-D planes
are infinite.</li>

<li><b>Convex Hulls.</b> A 3-D convex hull represents a shape described by the convex hull of zero or more points.</li>

</ulp>

<p>Functions are available to compute dot and cross products of vectors, to find the intersections of various
geometric forms, and to build convex hulls incrementally.</p>

<p>See also <xref dest="geometry"/>.</p>

</section>

<section name="characters"><title>Characters</title>

<p>Sunlit World Scheme, like the underlying dot-Net platform, uses 16-bit characters.</p>

<p>A character is written as <code>#\</code> followed by the character. This includes:</p>

<ul>
<li><code>#\#</code></li>
<li><code>#\\</code></li>
<li><code>#\(</code></li>
<li><code>#\)</code></li>
</ul>

<p>and so forth. Characters written in this way never get confused with other types of values. Some characters have
names instead:</p>

<ul>
<li><code>#\nul</code></li>
<li><code>#\bel</code></li>
<li><code>#\backspace</code></li>
<li><code>#\tab</code></li>
<li><code>#\newline</code></li>
<li><code>#\vt</code></li>
<li><code>#\page</code></li>
<li><code>#\return</code></li>
<li><code>#\space</code></li>
</ul>

<p>Finally, there is a way to specify 16-bit Unicode characters that cannot be represented by the codes above:</p>

<ul>
<li><code>#\x<var>code</var></code>, where <var>code</var> is a four-digit hexadecimal character code from
<code>0000</code> to <code>FFFF</code>. The hexadecimal digits <code>A</code> through <code>F</code> are
case-insensitive.</li>
</ul>

<p>Unicode code points above <code>65535</code> cannot be represented as single characters, and must be encoded using
surrogate pairs. Sunlit World Scheme imitates dot-Net by using the &ldquo;character&rdquo; type to represent an
unpaired surrogate.</p>

</section>

<section name="strings"><title>Strings</title>

<p>A string is a sequence of characters. As in standard Scheme, strings may be modified in place, but their length
cannot be changed.</p>

<p>A string is written as a begin-quote followed by a sequence of zero or more characters followed by an end-quote,
such as <code>""</code> (the empty string) or <code>"hello"</code>.</p>

<p>The backslash character <code>\</code> is used to mark escapes. Single character escapes are the same as in C
(<code>\&quot;</code>, <code>\\</code>, <code>\a</code> bell, <code>\b</code> backspace, <code>\t</code> tab,
<code>\n</code> newline, <code>\v</code> vertical tab, <code>\f</code> form feed, <code>\r</code> return), with the
addition of <code>\e</code> for escape.</p>

<p>Octal and hex escapes of the form <code>\<var>oct</var></code> and <code>\x<var>hex</var></code> are also supported
in strings, but only for characters 0-255. <var>oct</var> must be three digits and can range from <code>000</code>
to <code>377</code>, and <var>hex</var> must be two digits from <code>00</code> to <code>FF</code>. The hexadecimal
digits <code>A</code> through <code>F</code> are case-insensitive.</p>

<p>The implementation supports Unicode in strings. Characters are 16-bit; Unicode code points above <code>65535</code>
must be encoded using surrogate pairs. An extended hex escape can be used to specify any representable character,
regardless of whether it is representable by the escape codes above. It is written <code>\u<var>code</var></code>,
where <var>code</var> is replaced with any four-digit hexadecimal number, from <code>0000</code>
to <code>FFFF</code>.</p>

<p>See also <xref dest="func_strings"/>.</p>

</section>

<section name="symbols"><title>Symbols</title>

<p>A symbol is similar to a string, but symbols are immutable, and symbols with the same characters are guaranteed to
be equal. A symbol can be written as a string with pipe symbols, like <code>|abc|</code>, and all the same escapes can
be used in symbols that are used in strings, except that double-quotes do not need to be escaped and pipe symbols
do. In cases where no confusion with non-symbols is possible, the starting and ending pipes of a symbol may be
omitted, thus <code>abc</code> is the same as <code>|abc|</code>.</p>

</section>

<section name="lists"><title>Lists and Improper Lists</title>

<p>Lists are one of the fundamental data types of Scheme.</p>

<p>The empty list is represented as <code>()</code>. It may have spaces between the parentheses; such spaces are
ignored.</p>

<p>A non-empty list is represented by one or more <i>cons cells</i>, which are also known as <i>pairs</i>. A cons cell
is a record with two fields, a <i>car</i> and a <i>cdr</i>. The car contains the first item in the list, the
<i>head</i>, and the cdr contains the rest of the list, or <i>tail</i>.</p>

<p>The list <code>(1)</code> consists of a single cons cell. The car is the integer <code>1</code> and the cdr is
<code>()</code>, the empty list.</p>

<p>The list <code>(1 2 3)</code> consists of a cons cell whose car is <code>1</code> and whose cdr is the list
<code>(2 3)</code>, which in turn consists of a cons cell whose car is <code>2</code> and whose cdr is the list
<code>(3)</code>, and so forth.</p>

<p>The tail of a list is expected to be another list, including possibly the empty list. However, a cons cell does not
enforce this restriction, and it is possible to store any item in the cdr field of a cons cell. This gives rise to the
need for <i>dotted lists</i>, also known as <i>improper lists</i>.</p>

<p>The dotted list <code>(1 . 2)</code> consists of a cons cell whose car is <code>1</code> and whose cdr is
<code>2</code>. The dotted list <code>(1 2 . 3)</code> is a cons cell whose car is <code>1</code> and whose cdr is the
improper list <code>(2 . 3)</code>.</p>

<p>See also <xref dest="func_lists"/>.</p>

</section>

<section name="vector"><title>Vectors</title>

<p>A vector is written the same way as a list, but with the addition of a leading pound sign. <code>#(1 2 3)</code> is
a vector with three elements. A vector is stored as a deque of <code>object</code> and there are ways to change the
size of the vector by adding or removing items to or from either end. Dotted vectors are impossible.</p>

<p>See also <xref dest="func_vectors"/>.</p>

</section>

<section name="hashsetsandmaps"><title>Hash Sets and Hash Maps</title>

<p>A hash set is written the same way as a list, but with the addition of a leading pound sign and an <code>s</code>
meaning &ldquo;set.&rdquo; <code>#s(1 2 3)</code> is a set with three elements. The order of the elements does not
matter, and may vary. Only hashable items may be stored in a hash set.</p>

<p>A hash map is written the same way as a hash set, except that every item is required to be a pair. Only the first
item in the pair has to be hashable. Thus, <code>#m((one . 1) (two . 2) (three . 3))</code> is a hash map.</p>

<p>(If the second item in the pair is a list, the whole item will be printed as a list. Therefore, <code>#m((1 2
3))</code> is a valid hash map. It contains one pair. The key is <code>1</code> and the value for that key is the list
<code>(2 3)</code>.)</p>

<p>See also <xref dest="recursiveeval"/> and <xref dest="hashset"/>.</p>

</section>

<section name="messagesandsignatures"><title>Messages and Signatures</title>

<p>Messages and signatures are used by the object system. They can also be used in the same manner as Objective
Caml&rsquo;s &ldquo;variant types,&rdquo; or F#&rsquo;s &ldquo;discriminated unions.&rdquo;</p>

<p>A message has a type and zero or more key-value pairs known as arguments. The type must be a symbol, and the keys
of the arguments must be symbols. The values of the arguments can be of any Scheme type.</p>

<p>A signature has a type and zero or more parameters. The type must be a symbol and the parameters must be
symbols.</p>

<p>Every message has a corresponding signature with the same type symbol. The message&rsquo;s argument keys must be
the same as the corresponding signature&rsquo;s parameters.</p>

<p>A message with no arguments is written <code>#msg(<var>type</var>)</code>. A message with one or more arguments is
written <code>#msg(<var>type</var> . <var>key1</var> <var>value1</var> <var>key2</var> <var>value2</var>
<var>...</var>)</code>.</p>

<p>A signature with no parameters is written <code>#sig(<var>type</var>)</code>. A signature with one or more
parameters is written <code>#sig(<var>type</var> . <var>key1</var> <var>key2</var> <var>...</var>)</code>.</p>

<p>Arguments and parameters are order-insensitive.</p>

<p>See also <xref dest="recursiveeval"/>, <xref dest="mcase"/>, <xref dest="messagelambdas"/>,
<xref dest="func_messagesandsignatures"/>, and <xref dest="func_objects"/>.</p>

</section>

<section name="ipaddr"><title>IP Addresses and Endpoints</title>

<p>IP addresses are rarely typed literally, but it is possible.</p>

<p>An IPv4 address is written <code>#ipv4[<var>n</var>.<var>n</var>.<var>n</var>.<var>n</var>]</code>, where each
<var>n</var> is a number from <code>0</code> to <code>255</code> inclusive.</p>

<p>An IPv4 endpoint is an address followed by <code>:</code> and a port number from <code>0</code> to <code>65535</code>.
(I am not sure port zero is actually available.)</p>

<p>An IPv6 address is written <code>#ipv6[<var>addr</var>]</code>, where <var>addr</var> is a string consisting of
hexadecimals and colons. The exact format of the string is part of the IPv6 specification. Strings that do not match
the format cause lexical errors.</p>

<p>An IPv6 endpoint is an IPv6 address followed by <code>:</code> and a port number from <code>0</code> to
<code>65535</code>.</p>

<p>See also <xref dest="networking"/>.</p>

</section>

<section name="bytearray"><title>Byte Arrays, Byte Ranges, and Byte Rectangles</title>

<p>Objects of these types cannot be entered at the prompt, but they are very powerful and are commonly used for
I/O.</p>

<p>See also <xref dest="func_bytes"/>, <xref dest="byterange"/>, and <xref dest="byterect"/>.</p>

</section>

<section name="procedures"><title>Procedures</title>

<p>Procedures and functions are first-class values in Scheme. You cannot type a procedure directly, although you can
type an expression that produces a procedure. Scheme cannot display a procedure directly, either.</p>

<p>A <i>continuation</i> is a special type of procedure. A continuation is a function analogous to the
&ldquo;return&rdquo; statement in other languages. In Scheme, continuations can be captured. Sunlit World Scheme
supports continuations of unlimited extent, which means that a continuation remains valid after it has been
used. Scheme&rsquo;s &ldquo;stack frames&rdquo; persist, and are only deleted by garbage collection after they become
unreachable. A function can return its own continuation, and if this continuation is used, it gives the effect of the
function returning more than once. Continuations can be used to set up co-routines.</p>

<p>(However, continuations cannot be used to move from one thread to another.)</p>

<p>See also <xref dest="func_proc"/>.</p>

</section>

<section name="unspecified"><title>The Unspecified Value</title>

<p>Many procedures and syntaxes in Scheme return an <i>unspecified value.</i> The Scheme specification uses this term
to say that the procedure or syntax may return anything. However, many Scheme implementations have defined an actual
&ldquo;unspecified value&rdquo; and cause those procedures and syntaxes to return it. This Scheme follows that
tradition.</p>

</section>

<section name="other"><title>Other Types</title>

<p>Sunlit World Scheme supports many other types; in fact it uses the dot-Net <code>System.Object</code> type as its
underlying type, so any dot-Net object could appear as a parameter or result.</p>

</section>

</section>

<section name="syntaxes"><title>Syntaxes</title>

<p>In Scheme, a program is (typically) a list. The list is evaluated and the result printed on the screen.</p>

<p>Evaluation includes identifying syntaxes (and syntax errors) in the list. It is usually recursive.</p>

<p>Here are the syntaxes supported by Sunlit World Scheme.</p>

<section name="literals"><title>Self-Evaluating Literals</title>

<p>Booleans, integers, rationals, floats, characters, signatures, strings, 3-D vectors, and 3-D vertices evaluate to
themselves.</p>

</section>

<section name="quotation"><title>Quotation</title>

<p>The <code>quote</code> syntax has two forms, a long form and a short form.</p>

<ulp>

<li><b>The Short Form</b> is <code>'<var>data</var></code>. (The <code>'</code> is an apostrophe.)</li>

<li><b>The Long Form</b> is <code>(quote <var>data</var>)</code>.</li>

</ulp>

<p>The two forms are indistinguishable to the interpreter.</p>

<p>The form <code>(quote <var>data</var>)</code> always evaluates to <var>data</var>. This means that quoting one of
the self-evaluating data types above has no effect. But the point of <code>quote</code> is that it allows you to pass
literal lists, symbols, vectors, hash sets, or hash maps to functions. The evaluator would normally attempt to
interpret a list as a syntax and a symbol as a variable reference. A vector is traditionally
non-evaluable. <code>quote</code> causes
<var>data</var> to pass through the interpreter without being evaluated.</p>

</section>

<section name="quasiquotation"><title>Quasiquotation</title>

<p>Quasiquotation can be used to build new lists and vectors which consist of a combination of unchanging and changing
parts.</p>

<p>A syntax has the form <code>(quasiquote <var>qqdata</var>)</code> or <code>`<var>qqdata</var></code>. (The
<code>`</code> is a back-tick.)</p>

<p>The <var>qqdata</var> is examined by the quasiquote mechanism.</p>

<p>If <var>qqdata</var> contains <code>,<var>expr</var></code> or <code>(unquote <var>expr</var>)</code>, then
<var>expr</var> is evaluated and its value is substituted in place of the <code>,<var>expr</var></code> or
<code>(unquote <var>expr</var>)</code>.</p>

<p>If <var>qqdata</var> contains <code>,@<var>expr</var></code> or <code>(unquote-splicing <var>expr</var>)</code> in
a list, then <var>expr</var> is evaluated with the expectation that it evaluates to a list, and the list is spliced
into the place of <code>,@<var>expr</var></code> or <code>(unquote-splicing <var>expr</var>)</code>.</p>

<p>It is an error for an <code>unquote</code> or <code>unquote-splicing</code> form to appear outside of a
<code>quasiquote</code> form. It is an error for <code>unquote-splicing</code> to appear outside of a list, although
it is not an error for it to appear at the beginning or end of a list.</p>

<p>If <var>qqdata</var> contains a nested <code>`<var>qqdata</var></code> or <code>(quasiquote
<var>qqdata</var>)</code>, then <var>qqdata</var> is examined with a higher &ldquo;nesting count.&rdquo; Inside of a
nested <code>quasiquote</code>, nestings of <code>unquote</code> and <code>unquote-splicing</code> are detected. If
and only if they are nested to the same depth, then <var>expr</var> is evaluated and the substitution is made at the
bottom level of nesting. If <code>unquote</code>s and <code>unquote-splicing</code>s are not nested to sufficient
depth, then they are copied verbatim to the output.</p>

<p>Quasiquotation does not work with hash sets, hash maps, signatures, or messages.</p>

</section>

<section name="recursiveeval"><title>Recursively Evaluable Types</title>

<p>A couple of types are recursively evaluable. In other words, if an object of one of these types is presented for
evaluation, it is taken apart, some of the parts are evaluated, and then a new object is constructed replacing the
evaluated expressions with their values.</p>

<p>The hash map is one of these types. The keys are not evaluated, but the values are. Evaluating <code>#m((a . (+ 3
2)) (b . (+ 4 5)))</code> will give the result <code>#m((a . 5) (b . 9))</code>.</p>

<p>The other recursively evaluable type is the message. The type of the message and the argument keys are not
evaluted, but the argument values are evaluated. Evaluating <code>#msg(test . a (+ 7 1) b (+ 8 1))</code> will give
the result <code>#msg(test . a 8 b 9)</code>.</p>

<p>This was done to make up for the fact that these data types are not amenable to quasiquotation.</p>

<p>Evaluation always constructs and returns a new object.</p>

</section>

<section name="varref"><title>Variable References</title>

<p>Symbols such as <code>quote</code> are considered syntactic keywords. All symbols that are not syntactic keywords
are considered variable references.</p>

<p>The variable must be defined in the scope of its reference, or else it is an error.</p>

</section>

<section name="set"><title>set!</title>

<p>The syntax <code>(set! <var>var</var> <var>value</var>)</code> is used to change the value of a variable. The
<var>value</var> expression is evaluated recursively.</p>

<p>This syntax returns the unspecified value.</p>

<p>When a variable is first created, it is bound to a box in memory, and the contents are stored in the box. You can
change the contents of the box, but you cannot change which box a variable is bound to.</p>

</section>

<section name="begin"><title>Sequences</title>

<p>The syntax <code>(begin <var>item</var> <var>...</var>)</code> allows zero or more items to be evaluated in
sequence. If one or more items is provided, the value of the last is returned. If zero items are provided, the
unspecified value is returned.</p>

</section>

<section name="if"><title>If-then-else</title>

<p>The syntax <code>(if <var>test</var> <var>consequence</var> <var>alternate</var>)</code> represents an if-then-else
statement.</p>

<p>The syntax <code>(if <var>test</var> <var>consequence</var>)</code> is also valid.</p>

<p>First, <var>test</var> is evaluated. If it is <code>#f</code>, then the <var>alternate</var> is evaluated and its
value is returned. (If there is no <var>alternate</var>, the unspecified value is returned.) If the <var>test</var>
evaluates to non-<code>#f</code>, the <var>consequence</var> is evaluated and its value returned.</p>

</section>

<section name="cond"><title>Cond</title>

<p>The syntax <code>(cond <var>clause</var> <var>...</var>)</code> works like the &ldquo;if, else-if, else-if,
else&rdquo; found in other languages.</p>

<p>Each clause is of the form <code>(<var>test</var> <var>body</var> <var>...</var>)</code>. The <var>body</var> forms
are treated as if enclosed in a <code>begin</code>.</p>

<p>The <var>test</var> expression is evaluated. If the result is non-<code>#f</code>, the <var>body</var> forms for
that <var>clause</var> are evaluated and the result of the last one is returned. If the result is <code>#f</code>,
execution moves to the next <var>clause</var>.</p>

<p>The last clause may have a <var>test</var> of <code>else</code>, which causes the last clause to always be
executed.</p>

<p>If the <var>test</var> of the last clause fails, the unspecified value is returned.</p>

</section>

<section name="case"><title>Case</title>

<p>The syntax <code>(case <var>datum</var> <var>clause</var> <var>...</var>)</code> evaluates the expression for
<var>datum</var>, then uses a hash table to determine which <var>clause</var> should be executed. If <var>datum</var>
is not found and an <code>else</code> clause has been specified, the <code>else</code> clause is executed. The value
of the <code>case</code> form is the value of the last form in the clause that was executed.</p>

<p>The syntax of a <var>clause</var> is <code>((<var>item1</var> <var>item2</var> <var>...</var>) <var>action1</var>
<var>action2</var> ...)</code>. The <var>items</var> are not evaluated. Non-hashable <var>items</var> are ignored.</p>

</section>

<section name="mcase"><title>Message Case</title>

<p>The syntax <code>(mcase <var>datum</var> <var>clause</var> <var>...</var>)</code> evaluates the expression
for <var>datum</var>, expecting it to be a message. Then it binds variables for the message arguments and executes
the <var>clause</var> that matches the message, or, if none matches, the <code>else</code> clause.</p>

<p>The syntax of a <var>clause</var> is <code>(<var>msg</var> <var>body</var> <var>...</var>)</code>. The <var>msg</var>
must be either a message whose arguments are symbols to be bound to the actual message that matches, or a signature,
in which case the names of the symbols bound will be the names of the parameters.</p>

<p>For example, when <code>x</code> is <code>#msg(test . x 100 y 200)</code>:</p>

<ul>

<li>The expression <code>(mcase x (#msg(test . x a y b) (list a b)) (else #f))</code> will evaluate to <code>(100
200)</code>.</li>

<li>The expression <code>(mcase x (#sig(test . x y) (list x y)) (else #f))</code> will also evaluate to <code>(100
200)</code>.</li>

</ul>

</section>

<section name="local"><title>Object Fields (&ldquo;Locals&rdquo;)</title>

<p>Inside a Scheme object&rsquo;s message handler, it is possible to refer to the object&rsquo;s fields with the
<code>(local <var>var</var>)</code> syntax. <var>var</var> must be a symbol naming the object field being
referenced. <var>var</var> is not evaluated.</p>

<p>This syntax could not have been <code>(field <var>var</var>)</code> because there is a function
called <code>field</code> which is used for dot-Net reflection.</p>

<p>A field can be set with the syntax <code>(set!
(local <var>var</var>) <var>value</var>)</code>. Only <var>value</var> is evaluated.</p>

</section>

<section name="andor"><title>&ldquo;And&rdquo; And &ldquo;Or&rdquo;</title>

<p>Scheme supports short-circuiting <code>and</code> and <code>or</code> syntaxes.</p>

<p>They take the forms <code>(and <var>expr</var> <var>...</var>)</code> and <code>(or <var>expr</var>
<var>...</var>)</code>.</p>

<p>If <code>and</code> is called with zero <var>expr</var>s, it returns <code>#f</code>. If <code>or</code> is called
with zero <var>expr</var>s, it returns <code>#t</code>.</p>

<p>Otherwise <code>and</code> evaluates the forms from left to right, but if any <var>expr</var> returns
<code>#f</code>, <code>and</code> stops and returns <code>#f</code>. <code>or</code> evaluates from left to right, but
if any <var>expr</var> returns non-<code>#f</code>, <code>or</code> stops and returns that value.</p>

</section>

<section name="funcall"><title>Invocations</title>

<p><i>Invocations</i> are also known as <i>function calls</i> or <i>procedure calls.</i></p>

<p>The syntax of an invocation is <code>(<var>func</var> <var>arg</var> <var>...</var>)</code>.</p>

<p>The syntax permits zero or more <var>arg</var>s, but the proper number depends on which function is being
invoked.</p>

<p>The <var>func</var> and each <var>arg</var> are evaluated in some unspecified order.</p>

<p>The <var>func</var> is typically a reference to a variable that contains a function, but it can be any syntax that